delete from boardx_consultores;
insert into boardx_consultores (nombre,foto_url,tier,titular,especializacion,disciplinas,area,anios_experiencia,pais,idiomas,tarifa,moneda,bio,disponibilidad) values
('Ricardo Elizondo','https://i.pravatar.cc/150?u=cons-ricardo',1,'Ex-CFO, asesor financiero','Finanzas corporativas, M&A y levantamiento de capital','["Finanzas","M&A","Fundraising"]'::jsonb,'Financiera',22,'México','["Español","Inglés"]'::jsonb,450,'USD','22 años liderando finanzas en corporativos y scale-ups. Cerró +15 rondas de inversión.','disponible'),
('Valentina Ríos','https://i.pravatar.cc/150?u=cons-valentina',1,'Estratega comercial','Growth, pricing y expansión regional','["Comercial","Growth","Pricing"]'::jsonb,'Comercial',18,'Colombia','["Español","Inglés","Portugués"]'::jsonb,400,'USD','Escaló áreas comerciales de 0 a 8 dígitos en LATAM.','disponible'),
('Andrés Kaplan','https://i.pravatar.cc/150?u=cons-andres',1,'Operaciones y cadena de suministro','Lean, S&OP y eficiencia operativa','["Operativa","Lean","Supply Chain"]'::jsonb,'Operativa',20,'Argentina','["Español","Inglés"]'::jsonb,380,'USD','Optimizó operaciones de manufactura y logística en 3 países.','limitada'),
('María José Ferrer','https://i.pravatar.cc/150?u=cons-mariajose',2,'Talento y cultura','Atracción, retención y desarrollo de líderes','["Talento","Cultura","Liderazgo"]'::jsonb,'Talento',13,'España','["Español","Inglés","Francés"]'::jsonb,220,'USD','Construyó áreas de talento en empresas de alto crecimiento.','disponible'),
('Diego Salcedo','https://i.pravatar.cc/150?u=cons-diego',2,'Tecnología y datos','Transformación digital y arquitectura de datos','["Tecnología","Datos","Automatización"]'::jsonb,'Tecnología',12,'Chile','["Español","Inglés"]'::jsonb,240,'USD','Lideró la digitalización de PyMEs y medianas empresas.','disponible'),
('Paula Montenegro','https://i.pravatar.cc/150?u=cons-paula',2,'Legal corporativo','Contratos, gobierno corporativo y compliance','["Legal","Gobierno","Compliance"]'::jsonb,'Legal',15,'Perú','["Español","Inglés"]'::jsonb,210,'USD','Asesora legal de consejos y juntas directivas.','limitada'),
('Tomás Iglesias','https://i.pravatar.cc/150?u=cons-tomas',2,'Finanzas para PyMEs','Control financiero, costos y flujo de caja','["Finanzas","Costos","Flujo de caja"]'::jsonb,'Financiera',10,'México','["Español"]'::jsonb,180,'USD','Ordena las finanzas de PyMEs y las prepara para escalar.','disponible'),
('Camila Duarte','https://i.pravatar.cc/150?u=cons-camila',3,'Marketing y marca','Branding, contenido y adquisición','["Comercial","Marketing","Branding"]'::jsonb,'Comercial',6,'Uruguay','["Español","Inglés"]'::jsonb,110,'USD','Talento emergente en marketing de crecimiento.','disponible'),
('Sebastián Noriega','https://i.pravatar.cc/150?u=cons-sebastian',3,'Procesos y calidad','Documentación de procesos y mejora continua','["Operativa","Procesos","Calidad"]'::jsonb,'Operativa',5,'Colombia','["Español"]'::jsonb,95,'USD','Ayuda a estructurar procesos en empresas jóvenes.','disponible'),
('Lucía Herrera','https://i.pravatar.cc/150?u=cons-lucia',3,'People & operaciones','RRHH operativo y clima laboral','["Talento","RRHH","Clima"]'::jsonb,'Talento',4,'México','["Español","Inglés"]'::jsonb,90,'USD','Estructura el área de personas en etapas tempranas.','disponible'),
('Gabriel Fonseca','https://i.pravatar.cc/150?u=cons-gabriel',1,'Estrategia y dirección','Estrategia, OKRs y consejo directivo','["Estrategia","Gobierno","OKRs"]'::jsonb,'Financiera',25,'España','["Español","Inglés","Alemán"]'::jsonb,500,'USD','Consejero de múltiples boards; 25 años en dirección general.','disponible'),
('Fernanda Ocampo','https://i.pravatar.cc/150?u=cons-fernanda',3,'Tecnología / no-code','Automatización y herramientas no-code','["Tecnología","No-code","Automatización"]'::jsonb,'Tecnología',3,'Argentina','["Español","Inglés"]'::jsonb,85,'USD','Implementa automatizaciones rápidas para equipos pequeños.','disponible');
