import type { Pregunta } from '@/types/scanx';

/**
 * Profundización por ÁREA + preguntas CEO. Se preguntan DESPUÉS del tronco común,
 * solo en las áreas que el usuario confirmó en su perfil. Cada opción A/B/C/D mapea
 * a la madurez de ESA dimensión (Z/P/D/E). Algunos ítems llevan disparador de IA
 * (evidencia, timed challenge o repregunta).
 */
export type Disparador = 'evidencia' | 'timed' | 'repregunta';
export type PreguntaArea = Pregunta & {
  area: string;               // id de dimensión ('' = sin peso, p. ej. perfil CEO)
  disparador?: Disparador;
  repIA?: string;             // texto sugerido para la repregunta del agente
  soloSectores?: string[];    // si aplica solo a ciertos sectores
};

const E = 4.0, D = 2.67, P = 1.33, Z = 0.0;
const VALS = [Z, P, D, E];

function qa(area: string, id: string, pregunta: string, textos: [string, string, string, string], extra: Partial<PreguntaArea> = {}): PreguntaArea {
  return {
    id, area, escenario: pregunta,
    opciones: textos.map((t, i) => ({ id: `${id}${'abcd'[i]}`, texto: t, pesos: area ? { [area]: VALS[i] } : {} })),
    ...extra,
  };
}

/** Áreas: la clave es el nombre del área tal como se guarda en perfil.areas → dimensión. */
export const AREA_A_DIMENSION: Record<string, string> = {
  'Dirección / Estrategia': 'liderazgo',
  'Comercial / Ventas': 'comercial',
  'Marketing': 'comercial',
  'Operaciones': 'operacion',
  'Finanzas': 'finanzas',
  'Talento / RRHH': 'talento',
  'Tecnología / Sistemas': 'tecnologia',
  'Servicio al cliente': 'cliente',
  'Legal': 'liderazgo',
};

export const BANCO_AREAS: Record<string, PreguntaArea[]> = {
  liderazgo: [
    qa('liderazgo', 'lg01', '¿Quién toma las decisiones estratégicas en tu empresa?', ['Solo yo — no consulto ni delego decisiones importantes.', 'Yo, pero escucho opiniones de mi equipo cercano antes de decidir.', 'Hay un equipo directivo o comité que participa, aunque la última palabra es mía.', 'Las decisiones pasan por un consejo o comité con voto, y se documentan.'], { disparador: 'repregunta', repIA: '¿Alguna vez una decisión tuya generó un problema que se habría evitado consultando al equipo?' }),
    qa('liderazgo', 'lg02', '¿Tus líderes de área te presentan resultados formalmente?', ['No — yo voy y pregunto o me entero cuando hay un problema.', 'Me actualizan informalmente, en conversaciones o por WhatsApp.', 'Hay reportes o juntas periódicas, aunque a veces se saltan.', 'Cada líder presenta resultados con datos contra objetivos en juntas estructuradas.'], { disparador: 'evidencia', repIA: '¿Podrías mostrarnos un ejemplo de ese reporte o minuta?' }),
    qa('liderazgo', 'lg03', '¿Qué tanto delegas las decisiones del día a día?', ['Casi nada — todo pasa por mí, hasta las compras menores.', 'Delego lo operativo, pero reviso y apruebo la mayoría de las cosas.', 'Cada líder tiene autonomía, pero dinero o clientes importantes pasan por mí.', 'Hay niveles de autorización claros — cada quien sabe qué decide y qué necesita aprobación.']),
    qa('liderazgo', 'lg04', 'Si no pudieras dirigir la empresa por 6 meses, ¿quién la dirigiría?', ['No hay nadie — tendría que cerrar o pausar.', 'Alguien podría mantener lo básico, pero no dirigir realmente.', 'Alguien podría cubrirme en lo operativo, aunque no en lo estratégico.', 'Hay una persona o equipo preparado para asumir la dirección con claridad de funciones.'], { disparador: 'repregunta', repIA: '¿Esa persona sabe que tiene ese rol y tiene acceso a toda la información que necesitaría?' }),
    qa('liderazgo', 'lg05', '¿Tienes una visión clara de dónde quieres a tu empresa en 5 años?', ['No — voy resolviendo lo del día a día.', 'Tengo una idea vaga, pero no la he articulado ni compartido.', 'Sí, la tengo clara en mi cabeza, pero no está escrita ni formalizada.', 'Sí, está documentada, comunicada al equipo y con objetivos medibles.']),
    qa('liderazgo', 'lg06', '¿Tu empresa tiene valores definidos que realmente se viven?', ['No tenemos valores escritos — somos lo que somos.', 'Están escritos en algún lado, pero nadie los conoce o aplica.', 'El equipo los conoce y algunos se reflejan en cómo trabajamos.', 'Los valores son parte activa de la cultura: se usan en decisiones, se reconocen y evalúan.']),
    qa('liderazgo', 'lg07', '¿Existe un mecanismo formal de gobierno (consejo, junta de socios, comité directivo)?', ['No — todo es informal.', 'Existe en el acta constitutiva, pero no se reúne ni funciona.', 'Se reúne de vez en cuando, pero sin agenda ni seguimiento formal.', 'Funciona activamente con calendario, agenda, actas y seguimiento de acuerdos.'], { disparador: 'evidencia', repIA: '¿Con qué frecuencia se reúne y podrías compartir el acta de la última sesión?' }),
    qa('liderazgo', 'lg08', '¿Tu equipo tiene visibilidad de cómo va la empresa financieramente?', ['No — esa información es solo mía.', 'Comparto lo mínimo, como si vamos bien o mal en ventas.', 'Los líderes ven los números de su área, pero no el panorama completo.', 'Hay transparencia apropiada: cada nivel ve lo que necesita para decidir bien.']),
  ],
  estrategia: [
    qa('estrategia', 'ed01', '¿Tu empresa tiene un plan estratégico documentado?', ['No — la estrategia está en mi cabeza.', 'Tengo ideas escritas en notas sueltas, pero no un plan formal.', 'Hay un documento de plan, aunque no se revisa ni actualiza regularmente.', 'Sí — con objetivos, indicadores, responsables y revisión periódica.'], { disparador: 'evidencia', repIA: '¿Podrías compartir ese plan o las últimas notas de revisión?' }),
    qa('estrategia', 'ed02', '¿Las metas de tu empresa están descompuestas por área y persona?', ['No hay metas formales — cada quien hace lo que puede.', 'Hay una meta general (ventas, crecimiento), pero no descompuesta.', 'Los líderes tienen metas, pero no alineadas con una meta global.', 'Cascadeo claro: meta global → por área → individuales, con seguimiento.']),
    qa('estrategia', 'ed03', '¿Qué tanto conoces a tu competencia y el mercado donde operas?', ['Sé quiénes son, pero no los estudio formalmente.', 'Monitoreo a algunos competidores, pero no de forma sistemática.', 'Hago análisis de competencia periódicamente y conozco sus fortalezas y debilidades.', 'Tengo inteligencia de mercado: competencia, tendencias, precios y oportunidades.']),
    qa('estrategia', 'ed04', '¿Cómo se entera tu equipo de los cambios de dirección o prioridades?', ['Se enteran sobre la marcha — no hay comunicación formal.', 'Les aviso cuando hay algo importante, pero no de forma estructurada.', 'Hago reuniones generales de vez en cuando para comunicar dirección.', 'Hay un calendario de comunicación estratégica con reuniones, reportes y canales.']),
    qa('estrategia', 'ed05', '¿Las áreas trabajan alineadas hacia los mismos objetivos?', ['Cada área trabaja en lo suyo — hay poca coordinación.', 'Se coordinan cuando surge una necesidad, pero no permanentemente.', 'Los líderes se reúnen y coordinan, aunque a veces las prioridades chocan.', 'Objetivos compartidos entre áreas, reuniones de alineación y procesos establecidos.']),
    qa('estrategia', 'ed06', '¿Tienes identificados los principales riesgos que podrían afectar a la empresa?', ['No — nunca lo hemos pensado formalmente.', 'Los conozco de forma intuitiva, pero no están documentados.', 'Hemos identificado algunos riesgos clave, aunque sin plan de mitigación formal.', 'Tenemos un mapa de riesgos con probabilidad, impacto y plan de acción.']),
    qa('estrategia', 'ed07', '¿Podrías explicar a detalle cómo gana dinero tu empresa?', ['Sé que vendemos X y cobramos Y, pero no tengo un modelo articulado.', 'Puedo explicar las fuentes de ingreso, pero no cómo se relacionan con los costos.', 'Tengo claro el modelo y puedo explicarlo, aunque no está documentado.', 'El modelo está documentado: ingresos, costos, canales, segmentos, propuesta de valor.']),
    qa('estrategia', 'ed08', 'Cuando el mercado cambia (competidor, crisis, oportunidad), tu empresa suele…', ['Reaccionar tarde — nos damos cuenta cuando ya nos afectó.', 'Reaccionar rápido, pero sin plan — improvisamos soluciones.', 'Adaptarnos con algo de agilidad — ajustamos precios, productos o procesos.', 'Anticipar y preparar — monitoreamos y tenemos flexibilidad para pivotar rápido.']),
  ],
  operacion: [
    qa('operacion', 'op01', '¿Cuántos de tus procesos clave están mapeados o documentados?', ['Ninguno — todos trabajan por experiencia y costumbre.', 'Uno o dos medio documentados, el resto en la cabeza de alguien.', 'La mayoría están documentados, aunque algunos necesitan actualizarse.', 'Todos los procesos clave están documentados, actualizados y accesibles.'], { disparador: 'evidencia', repIA: 'Elige un proceso clave y comparte su documentación. ¿En cuánto tiempo puedes ubicarla?' }),
    qa('operacion', 'op02', '¿Tienes identificado el cuello de botella principal de tu operación?', ['No sé exactamente dónde está — a veces todo se atora y no sé por qué.', 'Tengo una idea, pero no he medido para confirmar.', 'Sí lo conozco, pero no lo he resuelto por falta de recursos o tiempo.', 'Lo identificamos con datos, tenemos un plan y lo estamos ejecutando.'], { disparador: 'repregunta', repIA: '¿Desde cuándo lo tienes identificado y qué has intentado hacer al respecto?' }),
    qa('operacion', 'op03', '¿Cómo verificas que lo que entregas cumple con la calidad esperada?', ['No hay verificación formal — confiamos en que la gente haga bien su trabajo.', 'El dueño o alguien de confianza revisa lo importante antes de entregar.', 'Hay puntos de control en el proceso, aunque no estandarizados para todo.', 'Proceso de calidad con criterios, checklist, auditorías y mejora continua.']),
    qa('operacion', 'op04', '¿Cumples consistentemente con los tiempos de entrega que prometes?', ['Frecuentemente nos retrasamos y los clientes se quejan.', 'A veces sí, a veces no — depende de la carga y los imprevistos.', 'Generalmente sí, con excepciones que manejamos avisando al cliente.', 'Casi siempre — medimos cumplimiento y estamos arriba del 90%.']),
    qa('operacion', 'op05', '¿Cómo manejas tu inventario o stock de materiales/productos?', ['A ojo — compro cuando veo que se está acabando algo.', 'Registro básico (Excel o cuaderno), pero no siempre al día.', 'Uso un sistema, aunque a veces no cuadra con la realidad.', 'Sistema preciso con mínimos, máximos, rotación y auditorías periódicas.'], { soloSectores: ['Manufactura', 'Comercio / Retail', 'Logística', 'Alimentos y Bebidas'] }),
    qa('operacion', 'op06', 'Si dos personas hacen la misma tarea, ¿la hacen de la misma manera?', ['No — cada quien tiene su forma y el resultado varía mucho.', 'Más o menos — hay una forma general pero cada quien le agrega su toque.', 'En los procesos principales sí hay estándar, en los secundarios no.', 'Sí — hay estándar para las tareas repetitivas y se verifica que se cumpla.']),
    qa('operacion', 'op07', '¿Qué tareas repetitivas se hacen manual y podrían automatizarse?', ['Casi todo manual — la tecnología que usamos es mínima.', 'Hay varias cosas automatizables pero no hemos invertido.', 'Hemos automatizado algo (facturación, reportes), pero quedan muchas.', 'La mayoría automatizadas y buscamos activamente qué más automatizar.']),
    qa('operacion', 'op08', '¿Existe un proceso para resolver de raíz los problemas recurrentes?', ['No — cuando pasa un problema se apaga el fuego y seguimos.', 'A veces analizamos qué salió mal, pero no de forma sistemática.', 'Se discuten en juntas y se buscan soluciones, aunque no siempre se implementan.', 'Mejora continua: se registran, analizan causas, implementan soluciones y verifican.']),
  ],
  comercial: [
    qa('comercial', 'cv01', '¿Tienes visibilidad de cuántos prospectos tienes, en qué etapa y cuándo cierran?', ['No — las ventas son lo que llega y se atiende.', 'Idea general en la cabeza o notas, pero no un pipeline formal.', 'Uso una herramienta o Excel, aunque no siempre está actualizado.', 'CRM con pipeline visible, métricas de conversión y pronóstico de ventas.'], { disparador: 'timed', repIA: '¿En cuánto tiempo puedes exportar tu pipeline de esta semana?' }),
    qa('comercial', 'cv02', '¿Tus vendedores siguen un proceso de venta definido?', ['Cada quien vende como puede — no hay proceso.', 'Hay lineamientos generales, pero cada vendedor tiene su estilo.', 'Hay un proceso que la mayoría sigue, con algunas variaciones.', 'Proceso estandarizado con etapas, guiones, materiales y capacitación.']),
    qa('comercial', 'cv03', '¿El equipo comercial tiene un esquema de comisiones o incentivos claro?', ['No hay comisiones ni incentivos — es sueldo fijo.', 'Hay comisiones, pero el cálculo no es claro o cambia seguido.', 'Esquema definido que el equipo conoce, aunque a veces genera dudas.', 'Transparente, motivante, alineado a los objetivos y se revisa periódicamente.']),
    qa('comercial', 'cv04', '¿Tu equipo de ventas recibe capacitación regularmente?', ['No — aprenden sobre la marcha.', 'De vez en cuando les doy tips o los mando a un curso.', 'Hay capacitación periódica, aunque sin programa estructurado.', 'Programa de desarrollo comercial continuo con temas, frecuencia y evaluación.']),
    qa('comercial', 'cv05', '¿Sabes cuántos prospectos necesitas contactar para cerrar una venta?', ['No tengo idea — no mido eso.', 'Idea vaga, pero no lo he calculado con datos.', 'Conozco mi tasa de conversión aproximada, aunque varía mucho.', 'Conozco mi conversión por etapa, por canal y por vendedor.']),
    qa('comercial', 'cv06', 'Cuando presentas una propuesta o cotización, ¿cómo es el proceso?', ['Le doy el precio de palabra o por WhatsApp y ya.', 'Cotización básica, sin diseño profesional ni diferenciación.', 'Plantilla de propuesta que personalizo para cada cliente.', 'Documento profesional con propuesta de valor, alcance, tiempos e inversión.']),
    qa('comercial', 'cv07', "Cuando un prospecto dice 'déjame pensarlo', ¿qué pasa?", ['Se pierde — no le damos seguimiento formal.', 'A veces le llamo después, pero depende de si me acuerdo.', 'Hay seguimiento, aunque no siempre se cumple con todos.', 'Entra a un flujo de seguimiento con recordatorios hasta cerrar o descartar.']),
    qa('comercial', 'cv08', '¿Cuántos canales de venta tiene tu empresa y cómo los manejas?', ['Solo uno (la tienda, mi red de contactos, etc.).', 'Dos o tres canales, pero no mido cuál genera más o mejor.', 'Varios canales y sé cuál genera más, aunque no todos optimizados.', 'Múltiples canales con estrategia diferenciada y métricas por canal.']),
  ],
  finanzas: [
    qa('finanzas', 'fr01', '¿Con qué frecuencia revisas tu estado de resultados?', ['No lo reviso — solo veo si hay dinero en la cuenta.', 'Cuando el contador me lo entrega, cada trimestre o cuando lo pido.', 'Lo reviso mensualmente, aunque a veces con retraso.', 'Mensualmente, con comparativo contra presupuesto y contra el mes anterior.']),
    qa('finanzas', 'fr02', '¿Puedes predecir cuánto efectivo tendrás disponible en 30 días?', ['No — voy día a día y a veces me sorprenden los pagos.', 'Idea general, pero no un flujo de caja proyectado.', 'Proyección básica, aunque no siempre precisa.', 'Flujo de caja proyectado que actualizo y es bastante preciso.'], { disparador: 'evidencia', repIA: '¿Podrías compartir tu flujo de caja proyectado actual?' }),
    qa('finanzas', 'fr03', '¿Las finanzas de la empresa están separadas de las tuyas personales?', ['No — uso la misma cuenta para todo.', 'Separadas en teoría, pero a veces mezclo gastos.', 'Cuentas separadas, aunque hago transferencias entre personal y empresa.', 'Completamente separadas — políticas de gastos, retiro de utilidades y compensación.']),
    qa('finanzas', 'fr04', '¿Cómo manejas la cobranza de tus cuentas por cobrar?', ['Cuando me acuerdo o cuando necesito el dinero, les llamo.', 'Alguien llama, pero sin proceso ni seguimiento sistemático.', 'Proceso con recordatorios, aunque algunos clientes se retrasan mucho.', 'Proceso automatizado con recordatorios y escalamiento; cartera vencida mínima.']),
    qa('finanzas', 'fr05', '¿Sabes cuánto necesitas vender al mes para cubrir tus gastos (punto de equilibrio)?', ['No lo he calculado.', 'Idea aproximada, pero no un número preciso.', 'Lo conozco, pero no lo actualizo cuando cambian los costos.', 'Lo conozco, lo actualizo y lo uso para decisiones de precio y volumen.']),
    qa('finanzas', 'fr06', '¿Cómo es la relación de tu empresa con la deuda?', ['Debo mucho y me cuesta pagar — los intereses me están comiendo.', 'Tengo deuda pero la manejo, aunque a veces me aprieta.', 'Manejable y estratégica, aunque podría estar mejor estructurada.', 'Bien estructurada, tasas competitivas y el apalancamiento es parte de mi estrategia.']),
    qa('finanzas', 'fr07', '¿Sabes cuáles productos/servicios son los más rentables y cuáles los menos?', ['No — vendo de todo sin diferenciar cuál me deja más.', 'Idea intuitiva, pero no lo he calculado.', 'Conozco los márgenes de los principales, aunque no de todos.', 'Análisis de rentabilidad por producto/servicio/cliente y decido con base en eso.']),
    qa('finanzas', 'fr08', '¿Cómo defines los precios de lo que vendes?', ['Igual que la competencia, o lo que siento que el mercado acepta.', 'Costo más un margen razonable, sin mucho análisis.', 'Fórmula de costeo y margen, pero no la reviso frecuentemente.', 'Estrategia con costos, mercado, valor percibido y diferenciación, revisada.']),
  ],
  talento: [
    qa('talento', 'te01', '¿Las personas saben exactamente qué se espera de ellas?', ['No — cada quien hace lo que cree que tiene que hacer.', 'Les digo verbalmente sus responsabilidades, pero no está escrito.', 'Hay descripciones de puesto, aunque no todas actualizadas.', 'Cada puesto tiene descripción, objetivos, competencias y se revisa.']),
    qa('talento', 'te02', '¿Cómo evalúas el desempeño de tu equipo?', ['No lo evalúo formalmente — sé quién jala por el día a día.', 'Doy retroalimentación cuando algo sale muy bien o muy mal.', 'Evaluaciones periódicas, aunque sin formato estandarizado.', 'Proceso formal con objetivos, retroalimentación 360° y plan de desarrollo.']),
    qa('talento', 'te03', '¿Con qué frecuencia se te va la gente de la empresa?', ['Mucho — la rotación es un problema constante.', 'Se van más de los que quisiera, pero no sé el porcentaje ni las razones.', 'Moderada y conozco las principales razones por las que se van.', 'Baja, mido el indicador, hago entrevistas de salida y actúo para retener.']),
    qa('talento', 'te04', '¿Los sueldos y beneficios que ofreces son competitivos con el mercado?', ['No sé — pago lo que puedo o lo que me piden.', 'Creo que estamos un poco abajo, pero es lo que la empresa puede dar.', 'Hemos comparado y estamos más o menos en línea.', 'Estudio de compensación actualizado, tabulador y prestaciones competitivas.']),
    qa('talento', 'te05', '¿Cómo describirías el ambiente de trabajo en tu empresa?', ['Tenso — hay problemas frecuentes entre personas o con la dirección.', 'Más o menos — sin problemas graves pero tampoco entusiasmo.', 'Bueno en general — la gente está cómoda, aunque hay mejoras.', 'Excelente — medimos clima, hay alta satisfacción y recomiendan trabajar aquí.']),
    qa('talento', 'te06', 'Cuando entra una persona nueva, ¿cómo es su primer mes?', ['Se sienta y empieza — aprende como puede preguntando.', 'Le explico o le asigno alguien, pero no hay un plan.', 'Inducción básica y alguien la acompaña los primeros días.', 'Onboarding con cronograma, materiales, mentor y evaluación final.']),
    qa('talento', 'te07', '¿Tus líderes de área saben liderar equipos o son operativos que terminaron siendo jefes?', ['Buenos técnicamente, pero nunca capacitados para liderar personas.', 'Algunos lideran bien por naturaleza, otros luchan con la gestión.', 'Hemos dado algo de capacitación en liderazgo, pero falta mucho.', 'Formación en gestión de personas, coaching y se evalúa su liderazgo.']),
    qa('talento', 'te08', '¿Las personas ven un futuro de crecimiento en tu empresa?', ['No hay hacia dónde crecer — los puestos son los que son.', 'Algunos han crecido, pero no hay un plan definido.', 'Hay oportunidades, aunque no formalizadas como plan de carrera.', 'Rutas de desarrollo claras y se promueve internamente.']),
  ],
  tecnologia: [
    qa('tecnologia', 'ts01', '¿Qué herramientas tecnológicas usa tu empresa en su operación diaria?', ['Lo básico: WhatsApp, Excel, correo. Quizá una red social.', 'Algunas herramientas (facturación, contabilidad), pero no integradas.', 'Varias herramientas por área, aunque no todas se comunican.', 'Ecosistema integrado donde las herramientas se alimentan y centralizan info.']),
    qa('tecnologia', 'ts02', 'Cuando implementas una herramienta nueva, ¿qué pasa?', ['La compro y ahí la dejo — quien quiera la usa.', 'La implemento yo e intento enseñar, pero no todos la adoptan.', 'Capacitación básica y seguimiento, aunque adopción desigual.', 'Proceso: evaluación, capacitación, soporte, medición de adopción y ajustes.']),
    qa('tecnologia', 'ts03', '¿Tu empresa genera reportes de desempeño con datos actualizados?', ['No — las decisiones se toman con intuición o experiencia.', 'El contador genera algunos financieros, pero no hay más.', 'Cada área genera sus reportes, pero no centralizados ni estandarizados.', 'Dashboards centralizados, actualizados casi en tiempo real, que el equipo consulta.'], { disparador: 'timed', repIA: '¿En cuánto tiempo puedes generar un reporte de ventas del último mes? Graba tu pantalla.' }),
    qa('tecnologia', 'ts04', '¿Qué tan fuerte es la presencia digital de tu empresa?', ['Casi nula — no tenemos sitio web ni redes activas.', 'Redes y quizá sitio web, pero descuidados o desactualizados.', 'Presencia activa y sitio funcional, pero sin estrategia de contenido clara.', 'Sitio optimizado, redes con estrategia, contenido regular y métricas.']),
    qa('tecnologia', 'ts05', '¿Cuántos de tus procesos repetitivos están automatizados?', ['Ninguno — todo es manual.', 'Facturación y quizá nómina, pero el resto manual.', 'Varios automatizados, pero quedan muchos manuales.', 'La mayoría automatizados y buscamos activamente qué más optimizar.']),
    qa('tecnologia', 'ts06', 'Cuando algo falla con la tecnología, ¿qué pasa?', ['Caos — nadie sabe qué hacer y se pierde tiempo.', 'Lo resolvemos como podemos, a veces llamamos a un técnico externo.', 'Tenemos soporte (interno o externo), aunque no siempre rápido.', 'Soporte definido con tiempos de respuesta y plan de continuidad para fallas críticas.']),
    qa('tecnologia', 'ts07', '¿Tu empresa usa inteligencia artificial en algún proceso?', ['No — no lo hemos explorado.', 'Alguien usa ChatGPT o similar personal, pero no es parte del proceso.', 'Probamos herramientas de IA en algún área, sin implementación formal.', 'Usamos IA de forma estratégica en uno o más procesos con resultados medibles.']),
    qa('tecnologia', 'ts08', '¿Tu empresa vende en línea?', ['No — todo es presencial o por contacto directo.', 'Recibimos pedidos por WhatsApp o redes, pero sin tienda en línea.', 'Tienda en línea o marketplace, pero no es el canal principal.', 'El canal digital es estratégico, con logística y métricas de e-commerce.']),
  ],
  cliente: [
    qa('cliente', 'cx01', '¿Qué tanto conoces a tu cliente ideal?', ['Vendemos a quien nos compra — no hay perfil definido.', 'Idea general de quién es, pero no documentado.', 'Hemos definido el cliente ideal, aunque no todo el equipo lo tiene claro.', 'Buyer personas con datos, el equipo las conoce y las usamos para decidir.']),
    qa('cliente', 'cx02', '¿Conoces todos los puntos de contacto del cliente con tu empresa?', ['No he pensado en eso — el cliente llega y lo atendemos.', 'Idea general, pero no lo he mapeado.', 'Conozco los principales, aunque hay algunos que no controlo.', 'Journey mapeado con puntos de contacto, fricción y oportunidades.']),
    qa('cliente', 'cx03', '¿Qué le ofreces a tu cliente después de que te compró?', ['Nada — si necesita algo, que nos llame.', 'Garantía o soporte básico si algo sale mal.', 'Seguimiento postventa y buscamos que vuelva a comprar.', 'Programa de postventa con seguimiento, fidelización, upselling y medición.']),
    qa('cliente', 'cx04', '¿Cómo maneja tu empresa las quejas o reclamaciones?', ['Las resuelve quien las recibe, como puede y sin registro.', 'Las atendemos, pero no las registramos ni analizamos patrones.', 'Se registran y resuelven, aunque no siempre en tiempos definidos.', 'Proceso con registro, tiempos, escalamiento y análisis para prevención.']),
    qa('cliente', 'cx05', '¿Qué porcentaje de tus ventas viene de clientes que ya te compraron?', ['No lo sé — no mido eso.', 'Creo que buena parte, pero no tengo el dato.', 'Lo mido aproximadamente.', 'Lo mido con precisión y tengo acciones para aumentar la recurrencia.']),
    qa('cliente', 'cx06', 'Si fueras tu propio cliente, ¿qué tan fácil sería comprarte?', ['Complicado — nuestro proceso es confuso o lento.', 'Funcional pero sin nada especial.', 'Buena experiencia, aunque hay puntos de fricción que conozco.', 'Excelente — diseñamos la experiencia intencionalmente y la mejoramos con feedback.']),
    qa('cliente', 'cx07', '¿Tus clientes te recomiendan activamente?', ['No sé — nunca lo he preguntado.', 'Creo que algunos sí (llegan referidos), pero no lo mido.', 'Pido testimonios o referencias de vez en cuando.', 'Mido NPS u otro indicador y tengo un programa de referidos activo.']),
    qa('cliente', 'cx08', '¿Tu empresa adapta su producto/servicio a cada cliente?', ['No — ofrecemos lo mismo para todos.', 'Nos adaptamos cuando el cliente lo pide, pero no proactivamente.', 'Tenemos opciones de personalización en algunos productos/servicios.', 'La personalización es parte de la propuesta de valor y adaptamos proactivamente.']),
  ],
  innovacion: [
    qa('innovacion', 'id01', '¿Las personas proponen ideas nuevas con frecuencia?', ['No — la gente hace lo que le toca y ya.', 'A veces alguien propone algo, pero no hay canal ni incentivo.', 'Se valoran las ideas y se implementan algunas, sin proceso formal.', 'Mecanismos formales para proponer, evaluar e implementar, y se reconoce a quien innova.']),
    qa('innovacion', 'id02', '¿Tu empresa invierte en desarrollar nuevos productos, servicios o mejoras?', ['No — vendemos lo que siempre hemos vendido.', 'Cuando surge una oportunidad improvisamos algo, sin inversión dedicada.', 'Destinamos algo de tiempo/recursos, aunque no constante.', 'Presupuesto y equipo dedicado a innovación con roadmap de productos.']),
    qa('innovacion', 'id03', '¿Cómo te mantienes al día con las tendencias de tu industria?', ['No lo hago — estoy ocupado con el día a día.', 'Leo algo de vez en cuando o me entero por conversaciones.', 'Asisto a eventos, leo o sigo líderes de forma semi-regular.', 'Proceso de monitoreo: eventos, investigación, pruebo tecnologías y las integro.']),
    qa('innovacion', 'id04', '¿Tienes algo genuinamente difícil de copiar para un competidor?', ['No realmente — cualquiera podría hacer lo que hacemos.', 'Experiencia y relaciones, pero nada tangible que nos proteja.', 'Know-how, procesos o tecnología propia, aunque no protegida formalmente.', 'Propiedad intelectual (marca, patentes, secreto, tecnología) con ventaja real.']),
    qa('innovacion', 'id05', 'Cuando decides implementar algo nuevo, ¿cuánto tarda en ejecutarse?', ['Mucho — las ideas se quedan en ideas.', 'Más de lo que debería — hay resistencia o falta de recursos.', 'En un tiempo razonable, aunque con fricciones.', 'Somos ágiles — probamos rápido, iteramos y escalamos lo que funciona.']),
    qa('innovacion', 'id06', '¿Cómo reacciona tu equipo cuando propones un cambio importante?', ["Resistencia — 'así lo hemos hecho siempre'.", 'Aceptan con desgano — lo hacen porque lo dice el jefe.', 'Apertura general, aunque algunos se resisten.', 'Lo reciben bien — están acostumbrados al cambio y participan en la solución.']),
  ],
  escalabilidad: [
    qa('escalabilidad', 'ec01', '¿Tu modelo de negocio se puede replicar en otra ubicación o con otro equipo sin ti?', ['No — todo gira alrededor de mí o de personas específicas.', 'Muy difícil — hay mucho conocimiento sin documentar.', 'Con esfuerzo sí — habría que documentar y capacitar mucho.', 'Sí — procesos replicables, modelo probado y equipo que lo opera sin mí.']),
    qa('escalabilidad', 'ec02', 'Si tu demanda aumentara 50% el próximo mes, ¿podrías atenderla?', ['Imposible — ya estamos al máximo.', 'Sería un caos, pero quizá cubriríamos bajando calidad.', 'Parte del crecimiento, pero necesitaríamos ajustes rápidos.', 'Sí — tenemos capacidad ociosa o podemos escalar rápido.']),
    qa('escalabilidad', 'ec03', '¿Tus sistemas actuales aguantarían el doble de volumen?', ['No — ya están al límite con lo actual.', 'Algunos sí, pero otros colapsarían — hay cuellos tecnológicos.', 'La mayoría aguantaría, pero habría que invertir en upgrades.', 'Diseñados para escalar — tecnología y procesos manejan crecimiento sin rediseño.']),
    qa('escalabilidad', 'ec04', '¿Tienes acceso a financiamiento si necesitaras invertir para crecer?', ['No — sin acceso a crédito ni capital.', 'Podría conseguir algo, pero difícil y en malas condiciones.', 'Acceso a líneas de crédito o inversionistas potenciales.', 'Financiamiento asegurado o reservas suficientes para un plan de crecimiento.']),
    qa('escalabilidad', 'ec05', '¿Tienes claro cuál es el camino para hacer crecer tu empresa?', ['No — simplemente trato de vender más de lo mismo.', 'Tengo ideas, pero no un plan de crecimiento definido.', 'Sé la oportunidad, pero me falta un plan ejecutable.', 'Estrategia clara con mercados target, modelo de expansión y timeline.']),
    qa('escalabilidad', 'ec06', '¿Tienes mentores, asesores o una red que te apoye en decisiones de crecimiento?', ['No — tomo todas las decisiones solo.', 'Consulto a amigos o colegas, pero no asesores formales.', 'Pertenezco a un grupo empresarial o tengo un asesor ocasional.', 'Consejo consultivo, mentores activos o redes que uso regularmente.']),
  ],
};

/** Preguntas del perfil del CEO/fundador (una sola vez). CEO-04 no tiene peso (4 caminos válidos). */
export const BANCO_CEO: PreguntaArea[] = [
  qa('liderazgo', 'ceo01', '¿Cuánto de tu tiempo dedicas a trabajar EN el negocio (operación) vs. SOBRE el negocio (estrategia)?', ['90% o más en operación — sin tiempo para estrategia.', '70-80% operación — de vez en cuando pienso en el futuro.', '50-50 — me fuerzo a dedicar tiempo a estrategia.', 'Más del 50% en estrategia — la operación funciona sin mí encima.']),
  qa('liderazgo', 'ceo02', '¿Inviertes en tu propio desarrollo como líder y empresario?', ['No — no tengo tiempo ni le veo necesidad.', 'Leo o veo videos, pero de forma informal.', 'Tomo cursos, asisto a eventos o leo con cierta regularidad.', 'Plan de desarrollo: cursos, mentoría, lectura, eventos, y aplico lo que aprendo.']),
  qa('liderazgo', 'ceo03', '¿Cómo es tu nivel de estrés y equilibrio vida-trabajo?', ['Agotado — la empresa me consume y afecta mi salud o relaciones.', 'Estresado frecuentemente, pero lo manejo como puedo.', 'Momentos de estrés y de balance — en un punto aceptable.', 'Equilibrio saludable — tiempo para mí, mi familia, y el negocio no depende 100% de mí.']),
  qa('', 'ceo04', '¿Qué quieres TÚ de esta empresa en los próximos 5-10 años?', ['Que me dé para vivir — es mi fuente de ingresos.', 'Que crezca para darme buena vida y patrimonio.', 'Construir algo grande que trascienda y genere impacto.', 'Que funcione sin mí — venderla, franquiciarla o que alguien más la opere.']),
  qa('liderazgo', 'ceo05', '¿Hay decisiones que deberías delegar pero no puedes soltar?', ['Sí, muchas — soy el cuello de botella principal y lo sé.', 'Algunas — cosas que solo yo sé hacer o no confío que otro las haga bien.', 'Pocas — he ido delegando, pero me cuesta soltar ciertos temas.', 'No — delego efectivamente y me enfoco en lo que solo yo puedo hacer.']),
  qa('estrategia', 'ceo06', 'Ante una oportunidad que requiere inversión importante, tú sueles…', ['No arriesgarme — prefiero lo seguro aunque crezca más lento.', 'Pensarlo mucho y generalmente no dar el paso por miedo.', 'Evaluarlo y dar el paso si los números tienen sentido, aunque nervioso.', 'Tomarlo con confianza — evalúo el riesgo, lo mitigo y avanzo.']),
  qa('finanzas', 'ceo07', '¿Qué tan cómodo te sientes con la parte financiera de tu empresa?', ['Me cuesta — los números no son lo mío, se lo dejo al contador.', 'Entiendo lo básico pero me falta profundidad para decidir.', 'Me manejo bien, aunque hay áreas que me gustaría dominar más.', 'Domino las finanzas — estados, indicadores y decido con confianza.']),
  qa('liderazgo', 'ceo08', '¿Cómo describiría tu equipo tu estilo de comunicación?', ['No comunico mucho — asumo que entienden lo que espero.', 'Comunico cuando es necesario, pero no soy constante.', 'Trato de comunicar regularmente, aunque a veces fallo.', 'Comunicador activo — comparto visión, reconozco logros, doy feedback y escucho.']),
  qa('escalabilidad', 'ceo09', '¿Cómo es tu red de contactos empresarial?', ['Casi inexistente — no busco networking.', 'Algunos contactos, pero no los cultivo ni aprovecho.', 'Red activa que uso para referidos o consultas.', 'Estratégica — la construyo intencionalmente y genera valor para mi empresa.']),
  qa('escalabilidad', 'ceo10', 'Si tu empresa cerrara mañana, ¿qué quedaría?', ['Nada — si yo no estoy, la empresa no existe.', 'Algunos clientes y relaciones, pero poco más.', 'Marca, procesos y un equipo que podría continuar con dirección.', 'Un negocio con valor propio — marca, procesos, clientes, equipo y sistemas.']),
];

/** Devuelve las preguntas de profundización para las áreas confirmadas + sector (oculta las que no aplican). */
export function preguntasDeAreas(areas: string[], sector?: string): PreguntaArea[] {
  const dims = new Set<string>();
  for (const a of areas ?? []) { const d = AREA_A_DIMENSION[a]; if (d) dims.add(d); }
  const out: PreguntaArea[] = [];
  for (const dim of Array.from(dims)) {
    for (const q of BANCO_AREAS[dim] ?? []) {
      if (q.soloSectores && sector && !q.soloSectores.includes(sector)) continue;
      out.push(q);
    }
  }
  return out;
}
